# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx --no-install prettier --write
        language: system
        files: \.(css|html|js|json|liquid|md|scss|ya?ml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        # Dev Containers use JSON with comments (JSONC), which this JSON parser does not support.
        exclude: ^\.devcontainer/devcontainer\.json$
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
